### ISSUE TITLE
Little error in cookie example?

### ISSUE THREAD

**Issue by Gabrielmtn** [glorious-codes/glorious-cookie#9]
I know it's a stupid bug, but with 
console.log(cookie); // { username: 'Rafael' }

are you logging out something that doesn't exist?

**Comment by mostafaebrahimi** [comment]
@Gabrielmtn  where is this line of code?

**Comment by mostafaebrahimi** [comment]
@Gabrielmtn  if you'r meaning was sample code in [website](https://glorious.codes/cookie) I must say that if you don't specify the key that need to be return by `gcookie.get(key)` by default it will be return all of your cookies so logging out here is true

**Comment by rafaelcamargo** [comment]
@mostafaebrahimi is right. It's explained [here](https://github.com/glorious-codes/glorious-cookie#get) on the documentation.

**Comment by rafaelcamargo** [comment]
@Gabrielmtn Shame on me. I think I get your point now. If you were alerting out about the missing "s" on the code, I have just [fixed](https://github.com/glorious-codes/glorious-codes/pull/31) it. Thank you so much for letting me know 👍
